version: "3.1"

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xTMYCxJv7hPw2NocSn4sAZbL9
      POSTGRES_USER: admin
      POSTGRES_DB: twitter-clone
      POSTGRES_HOST_AUTH_METHOD: password
    expose:
      - "5432"
  node_server:
    image: node:alpine
    restart: always
    working_dir: /home/app
    environment:
      POSTGRES_PASSWORD: xTMYCxJv7hPw2NocSn4sAZbL9
      POSTGRES_USER: admin
      POSTGRES_DB: twitter-clone
      POSTGRES_HOST: db
      NODE_ENV: dev
    volumes:
      - ./server:/home/app
    command: npm run server
    ports:
      - "5000:5000"
  react:
    image: node:16-alpine
    restart: always
    working_dir: /home/app
    volumes:
      - ./client:/home/app
    command: npm run start
    ports:
      - "80:3000"

volumes:
  database:

